import { sensorNames } from './config.js';
import { switchTab } from './ui.js';

export function generateCode() {
    const a0 = document.getElementById('selA0').value;
    const a2 = document.getElementById('selA2').value;
    const d2 = document.getElementById('selD2').value;
    const bmi = document.getElementById('chkBMI088').checked;
    const mma = document.getElementById('chkMMA7660').checked;
    
    // Fetch keys, use placeholders if empty
    const appEuiVal = document.getElementById('appEui').value.trim() || "INSERT_APP_EUI_HERE";
    const devEuiVal = document.getElementById('devEui').value.trim() || "INSERT_DEV_EUI_HERE";
    const appKeyVal = document.getElementById('appKey').value.trim() || "INSERT_APP_KEY_HERE";

    let code = `// --- GLR SMART CITY DATA COLLECTOR ---
// Automatically generated by the GLR Digital Portal

#include <Arduino.h>
#include <Wire.h>
#include <LoRaWan.h>
#include <TinyGPS++.h>
`;

    // INCLUDES & GLOBALS
    if (bmi) code += `#include "BMI088.h"\nBmi088Accel accel(Wire, 0x19);\nbool bmi_ok = false;\n`;
    if (mma) code += `#include <MMA7660.h>\nMMA7660 accelemeter;\nbool mma_ok = false;\n`;
    if (d2 === "DHT") {
        code += `#include "DHT.h"\n#define DHTPIN 2\n#define DHTTYPE DHT11 // Set to DHT22 if using the Pro version\nDHT dht(DHTPIN, DHTTYPE);\n`;
    }

    code += `
// --- LORA KEYS ---
char appEui[] = "${appEuiVal}"; 
char devEui[] = "${devEuiVal}";
char appKey[] = "${appKeyVal}";
const bool USE_LORA = true;

// --- CONNECTION STATE (Exponential Backoff) ---
bool isJoined = false;
unsigned long lastJoinAttempt = 0;
unsigned long joinInterval = 15000; // Start retrying after 15 seconds
const unsigned long MAX_JOIN_INTERVAL = 300000; // Cap retries at max 5 minutes

TinyGPSPlus gps;
char dataPayload[128];

// --- BLACK BOX MEMORY ---
struct SensorRecord {
    uint8_t hr;
    uint8_t min;
    uint8_t sec;
    float lat;
    float lng;
`;
    // DYNAMIC STRUCT FIELDS
    if (a0 === "TEMP") code += `    float a0_val;\n`;
    else if (a0 !== "NONE") code += `    float a0_val;\n`;
    
    if (a2 === "TEMP") code += `    float a2_val;\n`;
    else if (a2 !== "NONE") code += `    float a2_val;\n`;
    
    if (d2 === "BUTTON") code += `    int d2_val;\n`;
    else if (d2 === "ULTRASONIC") code += `    float d2_val;\n`;
    else if (d2 === "DHT") code += `    float d2_temp;\n    float d2_hum;\n`;

    if (bmi) code += `    float bmi_x, bmi_y, bmi_z;\n`;
    if (mma) code += `    float mma_x, mma_y, mma_z;\n`;

    code += `};
const int MAX_RECORDS = 300;
SensorRecord dataLog[MAX_RECORDS];
int recordCount = 0;

void setup() {
    Serial.begin(115200);
    Serial2.begin(9600); // GPS Comm
    
    // Enable power to the Grove sensors
    pinMode(38, OUTPUT);
    digitalWrite(38, HIGH);
    delay(500);
    
    Wire.begin();
    Serial.println("\\n--- GLR DATA COLLECTOR START ---");
`;

    if(bmi) code += `    if (accel.begin() >= 0) { bmi_ok = true; Serial.println("BMI088 I2C Found!"); }\n`;
    if(mma) code += `    accelemeter.init(); mma_ok = true; Serial.println("MMA7660 I2C Started!");\n`;

    if(a0 !== "NONE") code += `    pinMode(A0, INPUT);\n`;
    if(a2 !== "NONE") code += `    pinMode(A2, INPUT);\n`;
    if(d2 === "BUTTON") code += `    pinMode(2, INPUT);\n`;
    if(d2 === "DHT") code += `    dht.begin();\n`;

    code += `
    if (USE_LORA) {
        lora.init();
        lora.setKey(NULL, NULL, appKey);
        lora.setId(NULL, devEui, appEui);
        lora.setDeciveMode(LWOTAA); 
        Serial.println("Connecting to TTN...");
        
        if (lora.setOTAAJoin(JOIN, 20)) {
            isJoined = true;
            Serial.println("Successfully joined TTN!");
        } else {
            Serial.println("Join failed. Switching to offline logging with background retries.");
            lastJoinAttempt = millis();
        }
    }
}

void loop() {
    // 1. DATA COLLECTION & MATHEMATICS (Always runs)
    float lat = 0.0, lng = 0.0;
    uint8_t h = 0, m = 0, s = 0;
    
    if (gps.location.isValid()) { 
        lat = gps.location.lat(); 
        lng = gps.location.lng(); 
    }
    if (gps.time.isValid()) {
        h = gps.time.hour();
        m = gps.time.minute();
        s = gps.time.second();
    }

`;
    // SENSOR MATH A0
    if (a0 === "TEMP") {
        code += `    // A0: Calculate Temperature in Celsius (Steinhart-Hart equation)
    int a0_raw = analogRead(A0);
    float a0_val = 0.0;
    if(a0_raw > 0) {
        float R = 1023.0 / a0_raw - 1.0;
        R = 100000.0 * R;
        a0_val = 1.0 / (log(R/100000.0)/4275.0 + 1/298.15) - 273.15;
    }\n`;
    } else if (a0 !== "NONE") {
        code += `    // A0: Convert to Percentage (0-100%)
    float a0_val = (analogRead(A0) / 1023.0) * 100.0;\n`;
    }

    // SENSOR MATH A2
    if (a2 === "TEMP") {
        code += `    // A2: Calculate Temperature in Celsius (Steinhart-Hart equation)
    int a2_raw = analogRead(A2);
    float a2_val = 0.0;
    if(a2_raw > 0) {
        float R = 1023.0 / a2_raw - 1.0;
        R = 100000.0 * R;
        a2_val = 1.0 / (log(R/100000.0)/4275.0 + 1/298.15) - 273.15;
    }\n`;
    } else if (a2 !== "NONE") {
        code += `    // A2: Convert to Percentage (0-100%)
    float a2_val = (analogRead(A2) / 1023.0) * 100.0;\n`;
    }

    // SENSOR MATH D2
    if (d2 === "BUTTON") {
        code += `    // D2: Read Push Button
    int d2_val = digitalRead(2);\n`;
    } else if (d2 === "ULTRASONIC") {
        code += `    // D2: Calculate Ultrasonic Distance (Centimeters)
    pinMode(2, OUTPUT);
    digitalWrite(2, LOW); delayMicroseconds(2);
    digitalWrite(2, HIGH); delayMicroseconds(5);
    digitalWrite(2, LOW);
    pinMode(2, INPUT);
    long duration = pulseIn(2, HIGH, 30000); // 30ms timeout
    float d2_val = duration > 0 ? (duration / 29.0 / 2.0) : -1.0;\n`;
    } else if (d2 === "DHT") {
        code += `    // D2: Read Temperature & Humidity
    float d2_temp = dht.readTemperature();
    float d2_hum = dht.readHumidity();\n`;
    }

    // I2C SENSORS
    if (bmi) {
        code += `    float bmi_x = 0, bmi_y = 0, bmi_z = 0;
    if (bmi_ok) { accel.readSensor(); bmi_x = accel.getAccelX_mss(); bmi_y = accel.getAccelY_mss(); bmi_z = accel.getAccelZ_mss(); }\n`;
    }
    if (mma) {
        code += `    float mma_x = 0, mma_y = 0, mma_z = 0;
    if (mma_ok) { int8_t x,y,z; accelemeter.getXYZ(&x,&y,&z); mma_x = x; mma_y = y; mma_z = z; }\n`;
    }

    code += `
    // 2. SAVE TO BLACK BOX (Always runs)
    if (recordCount < MAX_RECORDS) {
        dataLog[recordCount].hr = h;
        dataLog[recordCount].min = m;
        dataLog[recordCount].sec = s;
        dataLog[recordCount].lat = lat;
        dataLog[recordCount].lng = lng;
`;
    if (a0 !== "NONE") code += `        dataLog[recordCount].a0_val = a0_val;\n`;
    if (a2 !== "NONE") code += `        dataLog[recordCount].a2_val = a2_val;\n`;
    if (d2 === "BUTTON" || d2 === "ULTRASONIC") code += `        dataLog[recordCount].d2_val = d2_val;\n`;
    if (d2 === "DHT") code += `        dataLog[recordCount].d2_temp = d2_temp;\n        dataLog[recordCount].d2_hum = d2_hum;\n`;
    
    if (bmi) code += `        dataLog[recordCount].bmi_x = bmi_x; dataLog[recordCount].bmi_y = bmi_y; dataLog[recordCount].bmi_z = bmi_z;\n`;
    if (mma) code += `        dataLog[recordCount].mma_x = mma_x; dataLog[recordCount].mma_y = mma_y; dataLog[recordCount].mma_z = mma_z;\n`;

    code += `        recordCount++;
    }

    // 3. LORA PAYLOAD GENERATION
`;
    
    let formatStr = `%.5f,%.5f`;
    let varStr = `lat, lng`;
    
    if(a0 !== "NONE") { formatStr += `,%.1f`; varStr += `, a0_val`; }
    if(a2 !== "NONE") { formatStr += `,%.1f`; varStr += `, a2_val`; }
    if(d2 === "BUTTON") { formatStr += `,%d`; varStr += `, d2_val`; }
    if(d2 === "ULTRASONIC") { formatStr += `,%.1f`; varStr += `, d2_val`; }
    if(d2 === "DHT") { formatStr += `,%.1f,%.1f`; varStr += `, d2_temp, d2_hum`; }

    code += `    snprintf(dataPayload, sizeof(dataPayload), "${formatStr}", ${varStr});

    Serial.print("-> Measurement Saved! LoRa Payload: ");
    Serial.println(dataPayload);
    
    // 4. SMART LORA TRANSMISSION WITH BACKOFF
    if (USE_LORA) {
        if (!isJoined) {
            // Check if it's time to retry joining
            if (millis() - lastJoinAttempt >= joinInterval) {
                Serial.print("Retrying TTN Join... ");
                if (lora.setOTAAJoin(JOIN, 20)) {
                    isJoined = true;
                    joinInterval = 15000; // Reset backoff timer upon success
                    Serial.println("Success! Now online.");
                    lora.transferPacket(dataPayload, 10);
                } else {
                    Serial.println("Failed.");
                    lastJoinAttempt = millis();
                    joinInterval *= 2; // Exponential backoff (double the wait time)
                    if (joinInterval > MAX_JOIN_INTERVAL) joinInterval = MAX_JOIN_INTERVAL;
                    Serial.print("Next attempt in ");
                    Serial.print(joinInterval / 1000);
                    Serial.println(" seconds.");
                }
            } else {
                Serial.println("Offline mode. Skipping LoRa transmission.");
            }
        } else {
            // We are joined, transmit the payload
            lora.transferPacket(dataPayload, 10);
        }
    }
    
    smartDelay(15000); 
}

// 5. THE DUMP COMMAND (For CSV Export)
void checkSerialCommand() {
    if (Serial.available()) {
        String cmd = Serial.readStringUntil('\\n');
        cmd.trim();
        if (cmd == "DUMP") {
            Serial.println("\\n\\n--- BEGIN BLACK BOX DATA DUMP ---");
            
            // Print the clean, design-ready CSV Header
            Serial.print("Time_UTC,Latitude,Longitude");`;

    if(a0 !== "NONE") code += ` Serial.print(",A0_${sensorNames[a0]}");`;
    if(a2 !== "NONE") code += ` Serial.print(",A2_${sensorNames[a2]}");`;
    
    if(d2 === "DHT") {
        code += ` Serial.print(",D2_Temperature_Celsius,D2_Humidity_Percent");`;
    } else if(d2 !== "NONE") {
        code += ` Serial.print(",D2_${sensorNames[d2]}");`;
    }
    
    if(bmi) code += ` Serial.print(",BMI_X,BMI_Y,BMI_Z");`;
    if(mma) code += ` Serial.print(",MMA_X,MMA_Y,MMA_Z");`;

    code += `
            Serial.println();

            for (int i = 0; i < recordCount; i++) {
                char timeBuf[10];
                snprintf(timeBuf, sizeof(timeBuf), "%02d:%02d:%02d", dataLog[i].hr, dataLog[i].min, dataLog[i].sec);
                Serial.print(timeBuf); Serial.print(",");
                
                Serial.print(dataLog[i].lat, 5); Serial.print(",");
                Serial.print(dataLog[i].lng, 5);
`;
    if(a0 !== "NONE") code += `                Serial.print(","); Serial.print(dataLog[i].a0_val, 1); \n`;
    if(a2 !== "NONE") code += `                Serial.print(","); Serial.print(dataLog[i].a2_val, 1); \n`;
    
    if(d2 === "BUTTON") code += `                Serial.print(","); Serial.print(dataLog[i].d2_val == HIGH ? "PRESSED" : "IDLE"); \n`;
    else if(d2 === "ULTRASONIC") code += `                Serial.print(","); Serial.print(dataLog[i].d2_val, 1); \n`;
    else if(d2 === "DHT") code += `                Serial.print(","); Serial.print(dataLog[i].d2_temp, 1); Serial.print(","); Serial.print(dataLog[i].d2_hum, 1); \n`;
    
    if(bmi) code += `                Serial.print(","); Serial.print(dataLog[i].bmi_x, 2); Serial.print(","); Serial.print(dataLog[i].bmi_y, 2); Serial.print(","); Serial.print(dataLog[i].bmi_z, 2);\n`;
    if(mma) code += `                Serial.print(","); Serial.print(dataLog[i].mma_x, 2); Serial.print(","); Serial.print(dataLog[i].mma_y, 2); Serial.print(","); Serial.print(dataLog[i].mma_z, 2);\n`;

    code += `                Serial.println();
            }
            Serial.println("--- END OF DATA DUMP ---\\n\\n");
        }
    }
}

static void smartDelay(unsigned long ms) {
    unsigned long start = millis();
    do {
        while (Serial2.available()) gps.encode(Serial2.read());
        checkSerialCommand();
    } while (millis() - start < ms);
}
`;

    document.getElementById('codeOutput').textContent = code;
    
    // Switch to Code Tab automatically upon compiling
    switchTab('code');
    document.getElementById('copyBtn').style.display = 'block';
}

export function copyCode() {
    const code = document.getElementById('codeOutput').textContent;
    navigator.clipboard.writeText(code).then(() => {
        const btn = document.getElementById('copyBtn');
        btn.innerHTML = "Copied to Clipboard! &check;";
        btn.classList.remove('bg-transparent', 'text-glr-neon');
        btn.classList.add('bg-glr-neon', 'text-black');
        setTimeout(() => {
            btn.innerHTML = "Copy to Clipboard";
            btn.classList.add('bg-transparent', 'text-glr-neon');
            btn.classList.remove('bg-glr-neon', 'text-black');
        }, 2000);
    });
}